baseURL = "https://escrinach.netlify.app/"
title = "IGNACIO ESCRIBANO OTT"
theme = "hugo-theme-m10c"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "INICIO"
    name = "INICIO"
    url = "/"
  [[menu.main]]
    identifier = "Tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Ignacio Escribano Ott"
  description = "Nutricionista y entrenador de baloncesto. Alto Rendimiento Deportivo. Investigación en métodos de recuperación y educación nutricional.ignacio.escribano.ott@gmail.com"
  avatar = "https://pbs.twimg.com/profile_images/1347498058679013377/jQMZU_wT_400x400.jpg"
  menu_item_separator = " - "
  [[params.social]]
    name = "researchgate"
    url = "https://www.researchgate.net/profile/Ignacio_Escribano-Ott"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/igeso"
  [[params.social]]
    name = "email"
    url ="mailto:ignacio.escribano.ott@gmail.com"
    


  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
